Zimbra/zm-zcs-lib

ivy.xml

This library is not actually used and its presence is
creating a conflict with the ZooKeeper library we are using.

ZCS-4346, ZCS-4315 Remove zkclient dependency

---

ivy.xml
pkg-builder.pl

upgrade guava jar to version 23.0
Upgrade the store and core pkgs to use the new version of guava jar.

ZCS-4723 Updating zm-zcs-lib with new version of guava

---

pkg-builder.pl

Address below build failure issue 
[exec] =========================================================================================================
[exec] FAILURE MSG : copy 'build/dist/mail-1.4.5.jar' -> 'build/stage/zimbra-common-core-libs/opt/zimbra/lib/jars/mail-1.4.5.jar' failed!
[exec] SYSTEM ERR  : No such file or directory
[exec]

NICPS-431: address build failure issue

---

.project
ivy.xml
pkg-builder.pl

Adding libraries required by ZCS which are no longer part of JDK 11.
Verified after adding these libraries  zmmailboxdctl restart is successful and ZCS web clieent and admin console function normally

ZCS-6714 Adding lib reqd. for JDK11 runtime

---

ivy.xml
pkg-builder.pl

Verified zmrestoreoffline -a "account" works without any ClassNotFound error
Verified that testcases in /data/backuprestore/commandline/zmrestoreoffline.rb pass

ZCS-6951 Fixing ClassNotFound Error

---

ivy.xml
pkg-builder.pl

issue : upgade to jetty 9.4.xxx or higher.
fix: removed old jetty dependencies and added new jetty version. there is some issue with the the jsp page loading. so added jetty jsp jar to zimbra class path. when server getting started, encountered some NoClassDefFound Exception, because the jetty servlet jar was not in the class path. so added both the jars to the service/WEB-INF/lib .
After adding these jars, server started successfully without any errors.
Linked PR:
https://github.com/Zimbra/zm-jetty-conf/pull/4
https://github.com/Zimbra/zm-mailbox/pull/903

zcs-6542:jetty upgrade to 9.4.15.xxx

---

ivy.xml
pkg-builder.pl

issue : upgrade jetty to 9.4.14 or higher.
fix : previously upgraded to 9.4.15.xxx which worked fine without any issue. As 9.4.18.xxx is the latest jetty version, its better to use it. so the changes has been done according to it.  It is working fine as expected with the latest version of jetty.
Testing:
QA needs to verify it.
Related PR
https://github.com/Zimbra/zm-mailbox/pull/908

zcs-6542:upgrade jetty to 9.4.18.xxx

---

pkg-builder.pl

Fixed issue faced while installing build created from feature/jetty9.4 branch.
Removed the lines copying jetty-servlets and jetty-servlet to service/WEB-INF/lib this now happens as part of service war.
Verified that the ZCS installer created with these changes installs without any issue.

ZCS-7320 Fixed issue faced while installing build 

---

pkg-builder.pl

Upgrading OWASP library to latest version, which resolves ZBUG-1148
Added fix for ZCS-7497 in new owasp library
Ref PRs:
https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/1
https://github.com/Zimbra/zm-build/pull/154
https://github.com/Zimbra/zm-mailbox/pull/963

ZBUG-1148:Loosing table format with owasp sanitizer

---

ivy.xml
pkg-builder.pl

Issue:  vulnerabilities in existing commons-compress jar 1.10
Fix: Upgrade commons-compress jar to the latest version 1.19
Related PRs:
https://github.com/Zimbra/zm-mailbox/pull/983
https://github.com/Zimbra/zm-genesis/pull/41
https://github.com/Zimbra/zm-soap-harness/pull/95

ZCS-8013: Third party vulnerabilities in commons-compress

---

ivy.xml
pkg-builder.pl

Issue:
commons-fileupload older version have vulnerabilities in older version.
Fix:
Updating version from 1.2.2 to 1.4
Related PRs:
https://github.com/Zimbra/zm-mailbox/pull/980
https://github.com/Zimbra/zm-genesis/pull/40
https://github.com/Zimbra/zm-soap-harness/pull/93
https://github.com/Zimbra/zm-taglib/pull/33
https://github.com/Zimbra/zm-clientuploader-store/pull/3
https://github.com/Zimbra/zm-clam-scanner-store/pull/2

ZCS-8016: updating commons fileupload version from 1.2.2 to 1.4

---

ivy.xml
pkg-builder.pl

Issue:
Vulnerabilities in older version 23.0 of Guava.
Fix:
Update version to 28.1-jre

ZCS-8017: updating guava version to 28.1-jre from 23.0

---

ivy.xml
pkg-builder.pl

Issue: Third-party vulnerabilities in Smack.
Fix: Removed these jar files as it's not used anywhere in the codebase.

ZCS-8009: Third party vulnerabilities in Smack

---

ivy.xml
pkg-builder.pl

Issue:
Vulnerabilities in older version 1.55 of bouncy castle.
Fix:
Update version to 1.64

ZCS-8010: updating bouncycastle version to 1.64 from 1.55

---

ivy.xml

Removing spring-asm as it is no longer required by apache-cxf

ZCS-8018 Removing spring-asm

---

ivy.xml
pkg-builder.pl

**Problem**: RemoteManager calls are failing with FIPS enabled.
https://jira.corp.synacor.com/browse/ZCS-10060?focusedCommentId=1419982&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1419982
Ganymed SSH-2 offering KexAlgorithms: `diffie-hellman-group-exchange-sha1`, `diffie-hellman-group14-sha1`, `diffie-hellman-group1-sha1` , which are not allowed in FIPS mode.
**Solution** : Replaced Ganymed SSH-2 with Trilead SSH-2 , which supports KexAlgorithms allowed in FIPS mode.

feature/ZCS-10060 : Upgraded SSH client library

---

ivy.xml
pkg-builder.pl

Added `tika-core` library for detecting the content-type and the file extension for the attachment.
**Related PR:**
[zm-build](https://github.com/Zimbra/zm-build/pull/180)
[zm-mailbox](https://github.com/Zimbra/zm-mailbox/pull/1132)

ZCS-10322: LDAP Attribute for supporting Attachment Type Restrictions

---

pkg-builder.pl

Update owasp-java-html-sanitizer version. 
https://files.zimbra.com/repository/owasp-java-html-sanitizer/owasp-java-html-sanitizer-20190610.2z.jar
However I recommend changing the owasp-java-html-sanitizer build process. 
I should create a jar from fork and running time/build and compile time we should the same jar.

update owasp-java-html-sanitizer version

---

ivy.xml
pkg-builder.pl

**Problem:**
When we use ssh-ed25519 in HostKeyAlgorithms, Apache MINA SSHD not able to communicate with OpenSSH.
**Fix:**
Apache MINA SSHD will not support ssh-ed25519 directly. To support ssh-ed25519 eddsa module must be added as an explicit dependency.
**Reference**
https://github.com/apache/mina-sshd/blob/2fc98f7a21a7b83d2b2bc72d48a2194caa7f8fd1/docs/dependencies.md

ZBUG-722: ed25519 support for Apache MINA SSHD

---

pkg-builder.pl

Bumped the version of owasp-java-html-sanitizer
**Reference PRs:**
[zm-mailbox PR1](https://github.com/Zimbra/zm-mailbox/pull/1145)
[zm-mailbox PR2](https://github.com/Zimbra/zm-mailbox/pull/1172)
[owasp-java-html-sanitizer](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/5)

ZBUG-1948: Bumped the version of owasp-java-html-sanitizer

---

ivy.xml
pkg-builder.pl

**Fix:**
Switching from tika-app-1.24.1.jar to tika-core-1.24.jar to fix `system failure: native formatter failure` while opening doc for editing.
**Note:**
After switching from tika-app-1.24.1.jar to tika-core-1.24.jar the above exception in the description is not reproducible. Following are the observations:
In case of Ubuntu when we use `attachment_extraction_client_class=com.zimbra.cs.convert.LegacyConverterClient`, there are issues while indexing and extraction is getting failed.
```
2021-07-02 09:26:42,714 INFO  [ReIndex-0] [name=akshat@shashi-classic-m1.synacor.tk;mid=2;] index - Re-index start
2021-07-02 09:26:42,715 INFO  [ReIndex-0] [name=akshat@shashi-classic-m1.synacor.tk;mid=2;] index - Resetting DB index data
2021-07-02 09:26:42,718 INFO  [ReIndex-0] …
```

ZCS-10598: Switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar

---

ivy.xml
pkg-builder.pl

**Problem:**
pdf/doc/docx contents not searchable after switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar
**Fix:**
Added jars which are necessary for the parsing and extraction of the documents which were not working after replacing `tika-app` jar to the `tika-core` jar. Now after adding these required jars like tika-parser and it's dependent jars the content of the search in the e-mail for the documents like `pdf, doc, docx, ppt, pptx, xls, xlsx`.
**Testing Done:**
- Verified on Ubuntu18 build contents of the attachment in e-mail for the above mentioned documents are searchable now.
- Verified on RHEL8 build contents of the attachment in e-mail for the above mentioned documents are searchable now.
**Related PRs:**
[zm-mailbox](https://github.com/Zimbra/zm-mailbox/pull/1173) …

ZCS-10728: pdf/doc/ppt/xls contents not searchable after switching from tika-app-1.24.1.jar to tika-core-1.24.1.jar

---

ivy.xml
pkg-builder.pl

**Problem:**
Briefcase uploads were not searchable
**Fix:**
While working on this found that while trying to create or edit the presentation following exception were getting observed:
- `java.lang.NoClassDefFoundError: Could not initialize class com.drew.imaging.jpeg.JpegMetadataReader`
- `java.lang.NoClassDefFoundError: com/adobe/internal/xmp/XMPException`
To fix these issues added the following dependencies to create and edit pptx presentation while using `TikaExtractorClient`:
- `metadata-extractor-2.16.0.jar`
- `xmpcore-6.1.11.jar`
**Testing Done:**
- Now, search is working in Briefcase.
- Verified now able to create and edit a presentation.
**Related PRs:**
[zm-mailbox](https://github.com/Zimbra/zm-mailbox/pull/1174)
[zm-convertd-store](https://github.com/Zimbra/zm-convertd-store/pull …

ZCS-10766: Briefcase uploads were not searchable

---

ivy.xml
pkg-builder.pl

Updated zm-zcs-lib ivy.xml and pkg-builder.pl, changed zm-ews-stub jar revision from 2.0 to 3.0.
This change is necessary as whenever we make changes in zm-ews-stub library we have to updated it's revision.
This changes shall be reviewed with old changes for zcs-4452
-  https://github.com/Zimbra/zm-ews-stub/pull/5/commits/0eebbd143212c83bca8d3e888d7e73c211f71c86
- https://github.com/Zimbra/zm-ews-store/pull/40/commits/6b14ad3e9d594d041900500d1a929d474d0f6e45

update zm-ews-stub jar version

---

ivy.xml
pkg-builder.pl

Related PRs:
[java-html-sanitizer#6](https://github.com/Zimbra/java-html-sanitizer-release-20190610.1/pull/6)
[zm-mailbox#1227](https://github.com/Zimbra/zm-mailbox/pull/1227)

ZBUG-1932: Upgrading owasp-java-html-sanitizer version

---

ivy.xml
pkg-builder.pl

Upgrade jetty to 9.4.46.v20220331
Related PR's:
https://github.com/Zimbra/zm-build/pull/205
https://github.com/Zimbra/zm-jetty-conf/pull/18
https://github.com/Zimbra/zm-mailbox/pull/1267

ZBUG-2633:Upgraded jetty to 9.4.46.v20220331

---

ivy.xml
pkg-builder.pl

Issue
With JDK 17 update there  is error in validating SAML response as SamlDereferencer cannot access class com.sun.org.apache.xml.internal.security.signature.XMLSignatureInput 
```
2022-06-07 03:30:48,986 INFO  [qtp252651381-115:https://zqa-226.eng.zimbra.com/service/extension/samlreceiver] [] extensions - Error in validating SAML response.
javax.xml.crypto.dsig.XMLSignatureException: javax.xml.crypto.URIReferenceException: java.lang.IllegalAccessException: class com.zimbra.cs.security.saml.SamlDereferencer cannot access class com.sun.org.apache.xml.internal.security.signature.XMLSignatureInput (in module java.xml.crypto) because module java.xml.crypto does not export com.sun.org.apache.xml.internal.security.signature to unnamed module @2c08c9e8
at …
```

ZCS-11505: update library com.sun.org.apache.xml.internal to org.apache.santuario for JDK 17 support

---

build.xml
pkg-builder.pl
scripts/postinst.sh

**Problem:**
`zimbra-common-core-libs` package deploys log4j-2.17.1 jar's.
while we installing zimlets, post install script of zimlets trying to execute `zmmailboxdctl status` and it's giving error .
`zmmailboxdctl` `zmlocalconfig` commands trying find old log4j-1.2.16 jar's because old zmlocalconfig file has old log4j-1.2.16 jar's  PATH in that.
See https://github.com/Zimbra/zm-core-utils/blob/9.0.0.p24/src/bin/zmlocalconfig#L57
**Fix:**
We have to copy updated zmlocalconfig file after `zimbra-common-core-libs` package has been installed. So post-install script has been added to update zmlocalconfig file (which has PATH of log4j-2.17.1 jar's)

ZCS-11514 : Getting log4j dependency errors while upgrading from Zimbra 9 Patch24.1 to Patch25

---

pkg-builder.pl

resolver-20050927.jar file not required as we moved to xmlsec-3.0.0.jar accroding to https://github.com/Zimbra/zm-zcs-lib/pull/97

ZCS-11505 : remove resolver-20050927.jar

---

ivy.xml
pkg-builder.pl

We have to included external JAR dependencies of following Jars for Open IO support, which needs to be included at path 'opt/zimbra/jetty_base/common/lib/'.
1. openio-api-2.0.3.jar
2. gson-2.8.2.jar
3. jackson-databind-2.10.1.jar
4. jackson-core-2.10.1.jar
5. jackson-annotations-2.10.1.jar
otherwise we use to get NoClassDefFoundException during server restart.

ZCS-11826 : Added dependencies for Open IO support

---

pkg-builder.pl

Update java-html-sanitizer-release version to fetch the latest version of jar when creating build.

ZBUG-2547: Update java-html-sanitizer-release version
