Zimbra/zm-zcs-lib

ivy.xml
=> ZCS-1877 updating zm-ews-stub version

build.xml, pkg-builder.pl
Adding target to build core and store pkgsfor third party libs.
Verified by creating pkg on Ubuntu 14 machines
=> ZCS-4355 Create core and store pkg for 3rd party lib

ivy.xml, pkg-builder.pl
Removed old jars from core pkg
Added new jars to the pkg
=> ZCS-4795 Add new jackson lib to core pkg

ivy.xml, pkg-builder.pl
Adding java-jwt-3.2.0.jar to the build.
=> ZCS-3349 Creating oauth-social build

ivy.xml
update javax mail library version to 1.6.2
=> NICPS-431: IDN

ivy.xml
This reverts commit 2a78789d7066bf930ebdf148b910eae7353adc5a.
=> Revert "NICPS-431: IDN (#29)"

pkg-builder.pl
[exec] 
[exec] =========================================================================================================
[exec] FAILURE MSG : copy 'build/dist/mail-1.4.5.jar' -> 'build/stage/zimbra-mbox-store-libs/opt/zimbra/jetty_base/common/lib/mail-1.4.5.jar' failed!
[exec] SYSTEM ERR  : No such file or directory
=> NICPS-431 - address build failure issue

ivy.xml, pkg-builder.pl
issue : throwing class not found exception while executing zmplayredo.
fix: added the dependency to that /lib/jars folder.
=> ZCS-6953 Fixing ClassNotFound Error

ivy.xml, pkg-builder.pl
Updated http client to latest version
=> ZCS-7494 Updating httpclient ver to latest

pkg-builder.pl
=> ZCS-7494 Removing old httpclient

ivy.xml, pkg-builder.pl
Upgraded the MariaDB connector to 2.4.3. Verified that mariadb related functionality works and   no exceptions are seen.
=> ZBUG-1099 Upgrading MariaDB connector to latest

ivy.xml, pkg-builder.pl
Ref PR: https://github.com/Zimbra/zm-mailbox/pull/961
=> ZBUG-711:convertd exhausts system memory when .har file is indexed

build.xml, ivy.xml, pkg-builder.pl
Upgrading owasp Antisamy library to latest version, with added fix for ZBUG-1174 in new antisamy library
Ref PRs:
https://github.com/Zimbra/zm-build/pull/157
https://github.com/Zimbra/zm-mailbox/pull/982
https://github.com/Zimbra/zm-zcs-lib/pull/57
https://github.com/Zimbra/antisamy/pull/1
=> ZBUG-1174: Web client does not show UTF-8 "Quoted-Printable"

ivy.xml, pkg-builder.pl
=> ZCS-8018 Upgrading CXF

ivy.xml, pkg-builder.pl
Issue: Third-party vulnerabilities in dom4j
Fix: Upgrade dom4j to the latest version
=> ZCS-8014: Third party vulnerabilities in dom4j

ivy.xml, pkg-builder.pl
Updating jars required by tika to a newer version
=> ZBUG-148 Updating jars required by Tika

ivy.xml, pkg-builder.pl
Updating Jar version required by Tika
=> ZBUG-148 Fixing Tika extractor

ivy.xml, pkg-builder.pl
Integrate Onlyoffice with Zimbra9
Adding required library for creating new document.
https://github.com/Zimbra/zm-mailbox/pull/1135
https://github.com/Zimbra/zm-jetty-conf/pull/15
=> adding required libs for onlyoffice new document creation

ivy.xml, pkg-builder.pl
**Problem:**
Apache MINA SSHD Client 2.6.0 not compatible with lower version of OpenSSH(<7).
**Fix:**
Update Apache MINA SSHD Client to latest version 2.6.1, and updated it's dependent jar's
=> ZBUG-2191 : Updated Apache MINA and it's dependent jar's

ivy.xml, pkg-builder.pl
Upgraded CXF jars and dependent Spring Jars
Verified EWS is working.
https://github.com/Zimbra/zm-mailbox/pull/1248
https://github.com/Zimbra/zm-ews-store/pull/45
=> ZCS-11282: updating apache cxf version

build.xml, pkg-builder.pl
Upgrading version to 8.8 with log4j upgrades
=> ZCS-11450 : Upgrading version of zmzimbratozimbramig to 8.8

ivy.xml, pkg-builder.pl
Updated version of jaxws-rt to 4.0.0
=> ZBUG-2998: Updated version of jaxws-rt to 4.0.0

ivy.xml, pkg-builder.pl
Upgraded Apache CXF jar's and dependent Spring Framework Jars
https://github.com/Zimbra/zm-mailbox/pull/1477
https://github.com/Zimbra/zm-ews-store/pull/52
=> ZBUG-3233 : Upgrade Apache CXF to 3.5.5

ivy.xml, pkg-builder.pl
Adding dependencies for the daemon-service in zm-license-tools
=> ZCS-14061 : adding dependency needed for zm-license-tools

ivy.xml, pkg-builder.pl
Ticket - [ZCS-14885](https://synacor.atlassian.net/browse/ZCS-14885)
added dependency for failureaccess
[ZCS-14885]: https://synacor.atlassian.net/browse/ZCS-14885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ZCS-14885: Getting Exception in thread main java.lang.NoClassDefFoundError: while running utility zmmboxsearch

pkg-builder.pl
Updated java-html-sanitizer-release version
=> ZBUG-3867 Update java-html-sanitizer-release version
